spring:
  profiles:
    active: "test"
---
spring:
  config:
    activate:
      on-profile: "test"
  application:
    name: deal
---
spring:
  config:
    activate:
      on-profile: "production"
  application:
    name: deal