spring:
  profiles:
    active: "test"
---
spring:
  config:
    activate:
      on-profile: "test"
  application:
    name: recruiting
  jpa:
    hibernate:
#      ddl-auto: create
      ddl-auto: validate
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog.xml
server:
  port: 8080
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
---
spring:
  config:
    activate:
      on-profile: "develop"
  application:
    name: recruiting
  jpa:
    hibernate:
#      ddl-auto: validate
          ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        format_sql: true
    show-sql: true
  datasource:
    driver: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/recruiting
    username: recruiting
    password: recruiting
---
spring:
  config:
    activate:
      on-profile: "production"
  application:
    name: recruiting
  jpa:
    hibernate:
      ddl-auto: validate
#          ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        format_sql: true
    show-sql: true
  datasource:
    driver: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/recruiting
    username: recruiting
    password: recruiting